import Link from 'next/link'
import {logOut} from '@/lib/auth'
//import './globals.css'
import NextTopLoader from 'nextjs-toploader';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark py-1" aria-label="Offcanvas navbar ">
        <div className="container-fluid">
          <Link className="navbar-brand" href="#">Airlink</Link>
          <button className="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
            <div className="offcanvas-header">
              <h5 className="offcanvas-title" id="offcanvasNavbar2Label">Offcanvas</h5>
              <button type="button" className="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div className="offcanvas-body">
              <ul className="navbar-nav me-auto flex-grow-1 pe-3">
                <li className="nav-item">
                  <Link className="nav-link active" aria-current="page" href="#">Home</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" href="#">Link</Link>
                </li>



              </ul>

            </div>
          </div>
          <div className="ms-auto d-flex gap-1" >
            <form className="d-flex" role="search">
              <div className="input-group input-group-sm">
                <input type="text" className="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" />
                <span className="input-group-text" id="inputGroup-sizing-sm"><i className='fa fa-search'></i></span>
              </div>
            </form>
            <ul className='navbar-nav'>
              <li className="nav-item dropdown">
                <button className=" dropdown-toggle btn btn-warning" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <span className="fa fa-user"></span>
                </button>
                <ul className="dropdown-menu dropdown-menu-end">
                  <li><Link className="dropdown-item" href="#">Profile</Link></li>
                  <li><Link className="dropdown-item" href="#">Another action</Link></li>
                  <li>
                    <hr className="dropdown-divider" />
                  </li>
                  <li><form action={logOut} ><button type="submit" className="dropdown-item" >Logout</button></form></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {children}
    </>
  )
}
